### ISSUE TITLE
Error when run "roslaunch realsense2_camera rs_camera.launch" with realsense D455

### ISSUE THREAD

**Issue by canglangzhige** [realsenseai/realsense-ros#2330]
I have done "catkin_make" successfully. But when I run "roslaunch realsense2_camera rs_camera.launch" with realsense D455, the errors occur in the terminal as follows:
[ INFO] [1650962486.250530086]: setupPublishers...
[ INFO] [1650962486.253286841]: Expected frequency for depth = 30.00000
[ INFO] [1650962486.273225919]: Expected frequency for color = 30.00000
[ INFO] [1650962486.288825662]: setupStreams...
[ INFO] [1650962486.318041076]: SELECTED BASE:Depth, 0
[ INFO] [1650962486.324823780]: RealSense Node Is Up!
[ WARN] [1650962486.577524282]: 
[ERROR] [1650962486.865507906]: hwmon command 0x75( 0 2cf 0 4ff ) failed (response -6= Invalid parameter)

Have can I solve it?

**Comment by MartyG-RealSense** [comment]
Hi @canglangzhige  In a couple of past cases where I have seen this error, it has occurred when the launch file has been edited to define RGB settings.  For example:

```
<rosparam>
/camera/rgb_camera/enable_auto_exposure: false
/camera/rgb_camera/enable_white_balance: false
</rosparam>
```

Have you altered the contents of your rs_camera.launch file in any way, please?

**Comment by canglangzhige** [comment]
I have solved the error when I reboot my PC. But I do not know why.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IntelRealSense/realsense-ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 下午5:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IntelRealSense/realsense-ros] Error when run "roslaunch realsense2_camera rs_camera.launch" with realsense D455 (Issue #2330)





 
Hi @canglangzhige  In a couple of past cases where I have seen this error, it has occurred when the launch file has been edited to define RGB auto epxosure settings.  For example:
 <rosparam&gt; /camera/rgb_camera/enable_auto_exposure: false /camera/rgb_camera/enable_white_balance: false </rosparam&gt;  
Have you altered your rs_camera.launch file in any way, please?

**Comment by MartyG-RealSense** [comment]
There are some problems that are not corrected by a camera reset or an unplug-replug of the USB cable and are only cleared by a complete shutdown to off state and then 'cold boot' of the computer with the power button.

**Comment by MartyG-RealSense** [comment]
Hi @canglangzhige  Do you require further assistance with this case, please?  Thanks!

**Comment by nevermore0127** [comment]
Still have this problem on ubuntu 20.04 + d435i , and i just tried all the reply you have done in realsense and realsense-ros's issues about 0x75 . but not work for me.  the cam works well for somedays ，then the problem ocurs ，i think i did nothing changed. so what can i do now . or what should i provide to you ? @MartyG-RealSense

**Comment by MartyG-RealSense** [comment]
Which method did you use to build the librealsense SDK. please?  From Debian packages or from source code?

Also, which librealsense and RealSense ROS wrapper versions are you using?  When building the wrapper from source code it is important to match a particular wrapper version as closely as possible with a specific librealsense version listed in the release notes for that wrapper version.

Would it be possible to paste your full launch log from the ROS terminal in a comment below?

**Comment by MartyG-RealSense** [comment]
Hi @nevermore0127   Do you require further assistance with your problem, please?  Thanks!

**Comment by nevermore0127** [comment]
i've changed a new  d435i camera . and it works. thanks！

在2022-05-16 ***@***.***写道：

Hi @nevermore0127 Do you require further assistance with your problem, please? Thanks!

**Comment by MartyG-RealSense** [comment]
That's great to hear, @nevermore0127 - thanks very much for the update!

As you have solved your problem with a camera change and the creator of this case @canglangzhige solved their problem with a reboot, I will close this case.  Thanks again!
