### ISSUE TITLE
Unable to turn off Depth Emitter by default

### ISSUE THREAD

**Issue by fiorano10** [realsenseai/realsense-ros#454]
| Required Info                         |                                                                |
|---------------------------------|------------------------------------------- |
| Camera Model                       |  D400  | 
| Firmware Version                   | 5.10.3 | 
| Operating System & Version |  Ubuntu 16.04  | 
| Kernel Version (Linux Only)    |  4.15.0-33-generic | 
| Platform                                 | PC |
| SDK Version                            | 2.15.0 | 
| Segment			|  Robot  | 

Even if I set the depth emitter to 0 in the cfg file, it still continues to work. The only way to shut it off is to have a bash script run the dynamic_reconfigure command to set it to 0.

**Comment by Rayman** [comment]
I fixed this issue in this PR: https://github.com/intel-ros/realsense/pull/481. Can you try it out?

**Comment by doronhi** [comment]
I tried PR #481. It didn't solve the problem, as I understand it. Admittedly, I didn't understand exactly what it does and I will be very happy with a more elaborated explanation since I don't consider myself a ROS expert.
However, I did find a problem in the initialization process of the reconfigurable parameters and fixed it in PR #499. @fiorano10 , Could you confirm that any of the PRs suggested here fix your problem?

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by fiorano10** [comment]
@doronhi The fix did work
