### ISSUE TITLE
Problem working with four d435 

### ISSUE THREAD

**Issue by Hunk86** [realsenseai/realsense-ros#756]
Hello,

I've the issue that i didn't get the pointcloud of all four cameras after I started them. The problem is that all cameras try to start on the same time. I'm able to solve this Problem when i replug a camera after I didn't get the polygon. (Workaround)

My launch file is the same as 

https://github.com/intel-ros/realsense/blob/development/realsense2_camera/launch/rs_multiple_devices.launch

only with 4 cameras

I have three questions :
1. What was your line of thinking when someone want to use more then one camera ? Should I write an own ros wrapper for this ? 
2. Is this a problem with the library or with the ros wrapper ? In my opinion more with the lib or?
3. Do you have an idea how i can solve this problem without replug the cameras ? 

Now the output of the logs. Did you need more information inside the log fills ?
I'm using ubuntu 18.04 and my Kernel is : 4.15.0-47-lowlatency

SUMMARY
========

PARAMETERS
 * /camera_front_bottom/realsense2_camera/accel_fps: 0
 * /camera_front_bottom/realsense2_camera/accel_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/accel_optical_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/align_depth: False
 * /camera_front_bottom/realsense2_camera/aligned_depth_to_color_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/base_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/calib_odom_file: 
 * /camera_front_bottom/realsense2_camera/clip_distance: 6.0
 * /camera_front_bottom/realsense2_camera/color_fps: 15
 * /camera_front_bottom/realsense2_camera/color_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/color_height: 480
 * /camera_front_bottom/realsense2_camera/color_optical_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/color_width: 640
 * /camera_front_bottom/realsense2_camera/depth_fps: 15
 * /camera_front_bottom/realsense2_camera/depth_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/depth_height: 480
 * /camera_front_bottom/realsense2_camera/depth_optical_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/depth_width: 640
 * /camera_front_bottom/realsense2_camera/enable_accel: True
 * /camera_front_bottom/realsense2_camera/enable_color: True
 * /camera_front_bottom/realsense2_camera/enable_depth: True
 * /camera_front_bottom/realsense2_camera/enable_fisheye1: True
 * /camera_front_bottom/realsense2_camera/enable_fisheye2: True
 * /camera_front_bottom/realsense2_camera/enable_fisheye: True
 * /camera_front_bottom/realsense2_camera/enable_gyro: True
 * /camera_front_bottom/realsense2_camera/enable_infra1: True
 * /camera_front_bottom/realsense2_camera/enable_infra2: True
 * /camera_front_bottom/realsense2_camera/enable_pointcloud: False
 * /camera_front_bottom/realsense2_camera/enable_sync: True
 * /camera_front_bottom/realsense2_camera/filters: pointcloud
 * /camera_front_bottom/realsense2_camera/fisheye1_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/fisheye1_optical_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/fisheye2_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/fisheye2_optical_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/fisheye_fps: 30
 * /camera_front_bottom/realsense2_camera/fisheye_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/fisheye_height: 0
 * /camera_front_bottom/realsense2_camera/fisheye_optical_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/fisheye_width: 0
 * /camera_front_bottom/realsense2_camera/gyro_fps: 0
 * /camera_front_bottom/realsense2_camera/gyro_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/gyro_optical_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/infra1_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/infra1_optical_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/infra2_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/infra2_optical_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/infra_fps: 30
 * /camera_front_bottom/realsense2_camera/infra_height: 480
 * /camera_front_bottom/realsense2_camera/infra_width: 640
 * /camera_front_bottom/realsense2_camera/initial_reset: True
 * /camera_front_bottom/realsense2_camera/linear_accel_cov: 0.01
 * /camera_front_bottom/realsense2_camera/odom_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/pointcloud_texture_index: 0
 * /camera_front_bottom/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera_front_bottom/realsense2_camera/pose_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/pose_optical_frame_id: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/publish_odom_tf: True
 * /camera_front_bottom/realsense2_camera/rosbag_filename: 
 * /camera_front_bottom/realsense2_camera/serial_no: 841512071306
 * /camera_front_bottom/realsense2_camera/topic_odom_in: camera_front_bott...
 * /camera_front_bottom/realsense2_camera/unite_imu_method: copy
 * /camera_front_top/realsense2_camera/accel_fps: 0
 * /camera_front_top/realsense2_camera/accel_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/accel_optical_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/align_depth: False
 * /camera_front_top/realsense2_camera/aligned_depth_to_color_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/base_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/calib_odom_file: 
 * /camera_front_top/realsense2_camera/clip_distance: 6.0
 * /camera_front_top/realsense2_camera/color_fps: 15
 * /camera_front_top/realsense2_camera/color_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/color_height: 480
 * /camera_front_top/realsense2_camera/color_optical_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/color_width: 640
 * /camera_front_top/realsense2_camera/depth_fps: 15
 * /camera_front_top/realsense2_camera/depth_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/depth_height: 480
 * /camera_front_top/realsense2_camera/depth_optical_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/depth_width: 640
 * /camera_front_top/realsense2_camera/enable_accel: True
 * /camera_front_top/realsense2_camera/enable_color: True
 * /camera_front_top/realsense2_camera/enable_depth: True
 * /camera_front_top/realsense2_camera/enable_fisheye1: True
 * /camera_front_top/realsense2_camera/enable_fisheye2: True
 * /camera_front_top/realsense2_camera/enable_fisheye: True
 * /camera_front_top/realsense2_camera/enable_gyro: True
 * /camera_front_top/realsense2_camera/enable_infra1: True
 * /camera_front_top/realsense2_camera/enable_infra2: True
 * /camera_front_top/realsense2_camera/enable_pointcloud: False
 * /camera_front_top/realsense2_camera/enable_sync: True
 * /camera_front_top/realsense2_camera/filters: pointcloud
 * /camera_front_top/realsense2_camera/fisheye1_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/fisheye1_optical_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/fisheye2_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/fisheye2_optical_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/fisheye_fps: 30
 * /camera_front_top/realsense2_camera/fisheye_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/fisheye_height: 0
 * /camera_front_top/realsense2_camera/fisheye_optical_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/fisheye_width: 0
 * /camera_front_top/realsense2_camera/gyro_fps: 0
 * /camera_front_top/realsense2_camera/gyro_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/gyro_optical_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/infra1_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/infra1_optical_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/infra2_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/infra2_optical_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/infra_fps: 30
 * /camera_front_top/realsense2_camera/infra_height: 480
 * /camera_front_top/realsense2_camera/infra_width: 640
 * /camera_front_top/realsense2_camera/initial_reset: True
 * /camera_front_top/realsense2_camera/linear_accel_cov: 0.01
 * /camera_front_top/realsense2_camera/odom_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/pointcloud_texture_index: 0
 * /camera_front_top/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera_front_top/realsense2_camera/pose_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/pose_optical_frame_id: camera_front_top_...
 * /camera_front_top/realsense2_camera/publish_odom_tf: True
 * /camera_front_top/realsense2_camera/rosbag_filename: 
 * /camera_front_top/realsense2_camera/serial_no: 841512071837
 * /camera_front_top/realsense2_camera/topic_odom_in: camera_front_top/...
 * /camera_front_top/realsense2_camera/unite_imu_method: copy
 * /camera_side_left/realsense2_camera/accel_fps: 0
 * /camera_side_left/realsense2_camera/accel_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/accel_optical_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/align_depth: False
 * /camera_side_left/realsense2_camera/aligned_depth_to_color_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/base_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/calib_odom_file: 
 * /camera_side_left/realsense2_camera/clip_distance: 6.0
 * /camera_side_left/realsense2_camera/color_fps: 15
 * /camera_side_left/realsense2_camera/color_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/color_height: 480
 * /camera_side_left/realsense2_camera/color_optical_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/color_width: 640
 * /camera_side_left/realsense2_camera/depth_fps: 15
 * /camera_side_left/realsense2_camera/depth_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/depth_height: 480
 * /camera_side_left/realsense2_camera/depth_optical_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/depth_width: 640
 * /camera_side_left/realsense2_camera/enable_accel: True
 * /camera_side_left/realsense2_camera/enable_color: True
 * /camera_side_left/realsense2_camera/enable_depth: True
 * /camera_side_left/realsense2_camera/enable_fisheye1: True
 * /camera_side_left/realsense2_camera/enable_fisheye2: True
 * /camera_side_left/realsense2_camera/enable_fisheye: True
 * /camera_side_left/realsense2_camera/enable_gyro: True
 * /camera_side_left/realsense2_camera/enable_infra1: True
 * /camera_side_left/realsense2_camera/enable_infra2: True
 * /camera_side_left/realsense2_camera/enable_pointcloud: False
 * /camera_side_left/realsense2_camera/enable_sync: True
 * /camera_side_left/realsense2_camera/filters: pointcloud
 * /camera_side_left/realsense2_camera/fisheye1_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/fisheye1_optical_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/fisheye2_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/fisheye2_optical_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/fisheye_fps: 30
 * /camera_side_left/realsense2_camera/fisheye_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/fisheye_height: 0
 * /camera_side_left/realsense2_camera/fisheye_optical_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/fisheye_width: 0
 * /camera_side_left/realsense2_camera/gyro_fps: 0
 * /camera_side_left/realsense2_camera/gyro_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/gyro_optical_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/infra1_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/infra1_optical_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/infra2_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/infra2_optical_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/infra_fps: 30
 * /camera_side_left/realsense2_camera/infra_height: 480
 * /camera_side_left/realsense2_camera/infra_width: 640
 * /camera_side_left/realsense2_camera/initial_reset: True
 * /camera_side_left/realsense2_camera/linear_accel_cov: 0.01
 * /camera_side_left/realsense2_camera/odom_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/pointcloud_texture_index: 0
 * /camera_side_left/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera_side_left/realsense2_camera/pose_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/pose_optical_frame_id: camera_side_left_...
 * /camera_side_left/realsense2_camera/publish_odom_tf: True
 * /camera_side_left/realsense2_camera/rosbag_filename: 
 * /camera_side_left/realsense2_camera/serial_no: 841612070826
 * /camera_side_left/realsense2_camera/topic_odom_in: camera_side_left/...
 * /camera_side_left/realsense2_camera/unite_imu_method: copy
 * /camera_side_right/realsense2_camera/accel_fps: 0
 * /camera_side_right/realsense2_camera/accel_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/accel_optical_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/align_depth: False
 * /camera_side_right/realsense2_camera/aligned_depth_to_color_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/base_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/calib_odom_file: 
 * /camera_side_right/realsense2_camera/clip_distance: 6.0
 * /camera_side_right/realsense2_camera/color_fps: 15
 * /camera_side_right/realsense2_camera/color_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/color_height: 480
 * /camera_side_right/realsense2_camera/color_optical_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/color_width: 640
 * /camera_side_right/realsense2_camera/depth_fps: 15
 * /camera_side_right/realsense2_camera/depth_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/depth_height: 480
 * /camera_side_right/realsense2_camera/depth_optical_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/depth_width: 640
 * /camera_side_right/realsense2_camera/enable_accel: True
 * /camera_side_right/realsense2_camera/enable_color: True
 * /camera_side_right/realsense2_camera/enable_depth: True
 * /camera_side_right/realsense2_camera/enable_fisheye1: True
 * /camera_side_right/realsense2_camera/enable_fisheye2: True
 * /camera_side_right/realsense2_camera/enable_fisheye: True
 * /camera_side_right/realsense2_camera/enable_gyro: True
 * /camera_side_right/realsense2_camera/enable_infra1: True
 * /camera_side_right/realsense2_camera/enable_infra2: True
 * /camera_side_right/realsense2_camera/enable_pointcloud: False
 * /camera_side_right/realsense2_camera/enable_sync: True
 * /camera_side_right/realsense2_camera/filters: pointcloud
 * /camera_side_right/realsense2_camera/fisheye1_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/fisheye1_optical_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/fisheye2_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/fisheye2_optical_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/fisheye_fps: 30
 * /camera_side_right/realsense2_camera/fisheye_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/fisheye_height: 0
 * /camera_side_right/realsense2_camera/fisheye_optical_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/fisheye_width: 0
 * /camera_side_right/realsense2_camera/gyro_fps: 0
 * /camera_side_right/realsense2_camera/gyro_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/gyro_optical_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/infra1_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/infra1_optical_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/infra2_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/infra2_optical_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/infra_fps: 30
 * /camera_side_right/realsense2_camera/infra_height: 480
 * /camera_side_right/realsense2_camera/infra_width: 640
 * /camera_side_right/realsense2_camera/initial_reset: True
 * /camera_side_right/realsense2_camera/linear_accel_cov: 0.01
 * /camera_side_right/realsense2_camera/odom_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/pointcloud_texture_index: 0
 * /camera_side_right/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera_side_right/realsense2_camera/pose_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/pose_optical_frame_id: camera_side_right...
 * /camera_side_right/realsense2_camera/publish_odom_tf: True
 * /camera_side_right/realsense2_camera/rosbag_filename: 
 * /camera_side_right/realsense2_camera/serial_no: 841512070503
 * /camera_side_right/realsense2_camera/topic_odom_in: camera_side_right...
 * /camera_side_right/realsense2_camera/unite_imu_method: copy
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /camera_front_top/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)
  /camera_front_bottom/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)
  /
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/state_publisher)
    rviz (rviz/rviz)
  /camera_side_right/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)
  /camera_side_left/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

[1mROS_MASTER_URI=http://localhost:11311[0m
[1mprocess[robot_state_publisher-1]: started with pid [3895][0m
[1mprocess[joint_state_publisher-2]: started with pid [3896][0m
[1mprocess[sick_safetyscanners/sick_safetyscanners-3]: started with pid [3903][0m
[1mprocess[camera_front_bottom/realsense2_camera_manager-4]: started with pid [3904][0m
[1mprocess[camera_front_bottom/realsense2_camera-5]: started with pid [3905][0m
[1mprocess[camera_front_top/realsense2_camera_manager-6]: started with pid [3910][0m
[1mprocess[camera_front_top/realsense2_camera-7]: started with pid [3912][0m
[1mp[0m[ INFO] [1556787999.361714897]: Initializing nodelet with 12 worker threads.[0m
[0m[ INFO] [1556787999.510105137]: RealSense ROS v2.2.3[0m
[0m[ INFO] [1556787999.510125104]: Running with LibRealSense v2.20.0[0m
[0m[ INFO] [1556788000.308886920]: Resetting device...[0m
[0m[ INFO] [1556788000.651192304]: Got a subscriber to scan, starting subscriber to pointcloud[0m
[0m[ INFO] [1556788004.720955382]: Checking new devices...[0m
 02/05 11:06:44,868 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
[0m[ INFO] [1556787999.323041529]: Initializing nodelet with 12 worker threads.[0m
[0m[ INFO] [1556787999.448139595]: RealSense ROS v2.2.3[0m
[0m[ INFO] [1556787999.448161184]: Running with LibRealSense v2.20.0[0m
[0m[ INFO] [1556788000.094017805]: Resetting device...[0m
[0m[ INFO] [1556788000.415675403]: Got a subscriber to scan, starting subscriber to pointcloud[0m
[0m[ INFO] [1556788004.721519883]: Checking new devices...[0m
[0m[ INFO] [1556788004.925925203]: getParameters...[0m
[0m[ INFO] [1556788004.991875945]: setupDevice...[0m
[0m[ INFO] [1556788005.365454025]: ROS Node Namespace: camera_front_bottom[0m
[0m[ INFO] [1556788005.365504317]: Device Name: Intel RealSense D435I[0m
[0m[ INFO] [1556788005.365552675]: Device Serial No: 841512071306[0m
[0m[ INFO] [1556788005.365599894]: Device FW version: 05.11.01.100
255.255.255.255[0m
[0m[ INFO] [1556788005.365652792]: Device Product ID: 0x0B3A[0m
[0m[ INFO] [1556788005.365724270]: Enable PointCloud: On[0m
[0m[ INFO] [1556788005.365766425]: Align Depth: Off[0m
[0m[ INFO] [1556788005.365807443]: Sync Mode: On[0m
[0m[ INFO] [1556788005.366496153]: Device Sensors: [0m
[0m[ INFO] [1556788005.366936427]: Stereo Module was found.[0m
[0m[ INFO] [1556788005.367043593]: RGB Camera was found.[0m
[0m[ INFO] [1556788005.367094571]: Motion Module was found.[0m
[0m[ INFO] [1556788005.367182127]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788005.367218744]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788005.367242760]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788005.367284514]: (Pose, 0) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788005.367906836]: setupPublishers...[0m
[0m[ INFO] [1556788005.374381042]: Expected frequency for depth = 15.00000[0m
[0m[ INFO] [1556788005.461041124]: Expected frequency for infra1 = 30.00000[0m
[0m[ INFO] [1556788005.519695002]: Expected frequency for infra2 = 30.00000[0m
[0m[ INFO] [1556788005.541326951]: Expected frequency for color = 15.00000[0m
[0m[ INFO] [1556788005.557735297]: Start publisher IMU[0m
[0m[ INFO] [1556788005.559674227]: setupStreams...[0m
 02/05 11:06:45,561 WARNING [139968031528704] (sensor.cpp:366) Unregistered Media formats : [ UYVY ]; Supported: [ ]
[0m[ INFO] [1556787999.343787840]: Initializing nodelet with 12 worker threads.[0m
[0m[ INFO] [1556787999.495074841]: RealSense ROS v2.2.3[0m
[0m[ INFO] [1556787999.495098010]: Running with LibRealSense v2.20.0[0m
[0m[ INFO] [1556788000.293481192]: Resetting device...[0m
[0m[ INFO] [1556788000.651301581]: Got a subscriber to scan, starting subscriber to pointcloud[0m
[0m[ INFO] [1556788004.721447774]: Checking new devices...[0m
 02/05 11:06:50,629 WARNING [139837780576000] (types.cpp:59) set_xu(ctrl=1) failed! Last Error: Input/output error
 02/05 11:06:50,629 WARNING [139837780576000] (rs.cpp:279) null pointer passed for argument "device"
 02/05 11:06:50,629 ERROR [139837780576000] (context.cpp:433) Exception thrown from user callback handler
[0m[ INFO] [1556787999.329277635]: Initializing nodelet with 12 worker threads.[0m
[0m[ INFO] [1556787999.468354945]: RealSense ROS v2.2.3[0m
[0m[ INFO] [1556787999.468377024]: Running with LibRealSense v2.20.0[0m
[0m[ INFO] [1556788000.325511369]: Resetting device...[0m
[0m[ INFO] [1556788000.648491981]: Got a subscriber to scan, starting subscriber to pointcloud[0m
[0m[ INFO] [1556788004.720105621]: Checking new devices...[0m
 02/05 11:06:56,329 WARNING [140523137537792] (types.cpp:59) set_xu(ctrl=1) failed! Last Error: Input/output error
 02/05 11:06:56,330 WARNING [140523137537792] (rs.cpp:279) null pointer passed for argument "device"
 02/05 11:06:56,330 ERROR [140523137537792] (context.cpp:433) Exception thrown from user callback handler
 02/05 11:07:02,029 WARNING [140366545995520] (types.cpp:59) set_xu(ctrl=1) failed! Last Error: Input/output error
 02/05 11:07:02,030 WARNING [140366545995520] (rs.cpp:279) null pointer passed for argument "device"
 02/05 11:07:02,030 ERROR [140366545995520] (context.cpp:433) Exception thrown from user callback handler
[0m[ INFO] [1556788036.269262407]: Checking new devices...[0m
 02/05 11:07:16,483 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
[0m[ INFO] [1556788036.355707191]: Checking new devices...[0m
 02/05 11:07:16,485 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,488 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,490 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,493 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,495 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,499 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,500 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,504 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,506 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,509 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,511 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,514 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,516 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,519 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,521 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,524 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,526 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,530 ERROR [139837780576000] (types.h:251) open() failed with all retries! Last Error: Device or resource busy
 02/05 11:07:16,530 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,531 ERROR [140523137537792] (types.h:251) open() failed with all retries! Last Error: Device or resource busy
 02/05 11:07:16,532 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,535 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,537 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,540 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,542 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,545 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,547 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,550 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,552 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,555 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,557 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,561 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,562 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,566 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,567 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,571 WARNING [139837780576000] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,573 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:16,576 ERROR [139837780576000] (types.h:251) open() failed with all retries! Last Error: Device or resource busy
 02/05 11:07:16,578 ERROR [140523137537792] (types.h:251) open() failed with all retries! Last Error: Device or resource busy
[0m[ INFO] [1556788037.050119722]: Checking new devices...[0m
 02/05 11:07:17,113 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,118 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,124 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,129 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,134 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,139 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,144 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,149 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,154 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,159 ERROR [140366545995520] (types.h:251) open() failed with all retries! Last Error: Device or resource busy
 02/05 11:07:17,160 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,165 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,170 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,175 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,180 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,185 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,191 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,196 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,201 WARNING [140366545995520] (backend-hid.cpp:610) open() failed!
 02/05 11:07:17,206 ERROR [140366545995520] (types.h:251) open() failed with all retries! Last Error: Device or resource busy
[0m[ INFO] [1556788036.827538979]: getParameters...[0m
[0m[ INFO] [1556788036.864024417]: setupDevice...[0m
[0m[ INFO] [1556788037.418453113]: ROS Node Namespace: camera_side_left[0m
[0m[ INFO] [1556788037.418465420]: Device Name: Intel RealSense D435I[0m
[0m[ INFO] [1556788037.418471276]: Device Serial No: 841612070826[0m
[0m[ INFO] [1556788037.418477666]: Device FW version: 05.11.01.100
255.255.255.255[0m
[0m[ INFO] [1556788037.418483444]: Device Product ID: 0x0B3A[0m
[0m[ INFO] [1556788037.418494135]: Enable PointCloud: On[0m
[0m[ INFO] [1556788037.418499566]: Align Depth: Off[0m
[0m[ INFO] [1556788037.418505355]: Sync Mode: On[0m
[0m[ INFO] [1556788037.418716808]: Device Sensors: [0m
[0m[ INFO] [1556788037.418836740]: Stereo Module was found.[0m
[0m[ INFO] [1556788037.418863324]: RGB Camera was found.[0m
[0m[ INFO] [1556788037.418874053]: Motion Module was found.[0m
[0m[ INFO] [1556788037.418897217]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788037.418906527]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788037.418912165]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788037.418918241]: (Pose, 0) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788037.419135715]: setupPublishers...[0m
[0m[ INFO] [1556788037.420969460]: Expected frequency for depth = 15.00000[0m
[0m[ INFO] [1556788037.443743686]: Expected frequency for infra1 = 30.00000[0m
[0m[ INFO] [1556788037.456211856]: Expected frequency for infra2 = 30.00000[0m
[0m[ INFO] [1556788037.469921781]: Expected frequency for color = 15.00000[0m
[0m[ INFO] [1556788037.482636421]: Start publisher IMU[0m
[0m[ INFO] [1556788037.484270159]: setupStreams...[0m
 02/05 11:07:17,485 WARNING [139837780576000] (sensor.cpp:366) Unregistered Media formats : [ UYVY ]; Supported: [ ]
[0m[ INFO] [1556788037.319990084]: getParameters...[0m
[0m[ INFO] [1556788037.348326089]: setupDevice...[0m
[0m[ INFO] [1556788037.956268212]: ROS Node Namespace: camera_side_right[0m
[0m[ INFO] [1556788037.956284213]: Device Name: Intel RealSense D435I[0m
[0m[ INFO] [1556788037.956291377]: Device Serial No: 841512070503[0m
[0m[ INFO] [1556788037.956297977]: Device FW version: 05.11.01.100
255.255.255.255[0m
[0m[ INFO] [1556788037.956305352]: Device Product ID: 0x0B3A[0m
[0m[ INFO] [1556788037.956314285]: Enable PointCloud: On[0m
[0m[ INFO] [1556788037.956321071]: Align Depth: Off[0m
[0m[ INFO] [1556788037.956328681]: Sync Mode: On[0m
[0m[ INFO] [1556788037.956545864]: Device Sensors: [0m
[0m[ INFO] [1556788037.956722186]: Stereo Module was found.[0m
[0m[ INFO] [1556788037.956750954]: RGB Camera was found.[0m
[0m[ INFO] [1556788037.956763313]: Motion Module was found.[0m
[0m[ INFO] [1556788037.956788588]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788037.956797819]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788037.956804836]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788037.956812493]: (Pose, 0) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788037.956979663]: setupPublishers...[0m
[0m[ INFO] [1556788037.958728411]: Expected frequency for depth = 15.00000[0m
[0m[ INFO] [1556788037.981671160]: Expected frequency for infra1 = 30.00000[0m
[0m[ INFO] [1556788037.994970743]: Expected frequency for infra2 = 30.00000[0m
[0m[ INFO] [1556788038.008356512]: Expected frequency for color = 15.00000[0m
[0m[ INFO] [1556788038.021512818]: Start publisher IMU[0m
[0m[ INFO] [1556788038.023085817]: setupStreams...[0m
 02/05 11:07:18,024 WARNING [140366545995520] (sensor.cpp:366) Unregistered Media formats : [ UYVY ]; Supported: [ ]
 02/05 11:07:22,527 WARNING [140523137537792] (types.cpp:59) set_xu(ctrl=1) failed! Last Error: Input/output error
 02/05 11:07:22,528 WARNING [140523137537792] (rs.cpp:279) null pointer passed for argument "device"
 02/05 11:07:22,528 ERROR [140523137537792] (context.cpp:433) Exception thrown from user callback handler
[0m[ INFO] [1556788077.581117601]: Checking new devices...[0m
 02/05 11:07:57,800 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,805 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,810 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,816 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,821 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,826 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,831 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,836 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,841 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,847 ERROR [140523137537792] (types.h:251) open() failed with all retries! Last Error: Device or resource busy
 02/05 11:07:57,847 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,852 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,857 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,862 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,867 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,873 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,878 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,883 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,888 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:57,893 ERROR [140523137537792] (types.h:251) open() failed with all retries! Last Error: Device or resource busy
 02/05 11:07:58,053 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,058 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,064 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,069 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,074 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,079 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,084 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,089 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,095 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,100 ERROR [140523137537792] (types.h:251) open() failed with all retries! Last Error: Device or resource busy
 02/05 11:07:58,100 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,105 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,110 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,116 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,121 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,126 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,131 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,136 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,141 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,146 ERROR [140523137537792] (types.h:251) open() failed with all retries! Last Error: Device or resource busy
 02/05 11:07:58,307 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,313 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,318 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,323 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,328 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,333 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,338 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,343 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,349 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,354 ERROR [140523137537792] (types.h:251) open() failed with all retries! Last Error: Device or resource busy
 02/05 11:07:58,354 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,359 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,364 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,369 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,374 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,380 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,385 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,390 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,395 WARNING [140523137537792] (backend-hid.cpp:610) open() failed!
 02/05 11:07:58,400 ERROR [140523137537792] (types.h:251) open() failed with all retries! Last Error: Device or resource busy
[0m[ INFO] [1556788078.518020832]: getParameters...[0m
[0m[ INFO] [1556788078.552244239]: setupDevice...[0m
[0m[ INFO] [1556788079.309585361]: ROS Node Namespace: camera_front_top[0m
[0m[ INFO] [1556788079.309602062]: Device Name: Intel RealSense D435I[0m
[0m[ INFO] [1556788079.309610306]: Device Serial No: 841512071837[0m
[0m[ INFO] [1556788079.309620429]: Device FW version: 05.11.01.100
255.255.255.255[0m
[0m[ INFO] [1556788079.309628741]: Device Product ID: 0x0B3A[0m
[0m[ INFO] [1556788079.309636185]: Enable PointCloud: On[0m
[0m[ INFO] [1556788079.309643142]: Align Depth: Off[0m
[0m[ INFO] [1556788079.309650346]: Sync Mode: On[0m
[0m[ INFO] [1556788079.309979775]: Device Sensors: [0m
[0m[ INFO] [1556788079.310158794]: Stereo Module was found.[0m
[0m[ INFO] [1556788079.310199578]: RGB Camera was found.[0m
[0m[ INFO] [1556788079.310225173]: Motion Module was found.[0m
[0m[ INFO] [1556788079.310267543]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788079.310284762]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788079.310299161]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788079.310312475]: (Pose, 0) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1556788079.310480180]: setupPublishers...[0m
[0m[ INFO] [1556788079.312661902]: Expected frequency for depth = 15.00000[0m
[0m[ INFO] [1556788079.335085552]: Expected frequency for infra1 = 30.00000[0m
[0m[ INFO] [1556788079.350111510]: Expected frequency for infra2 = 30.00000[0m
[0m[ INFO] [1556788079.363225456]: Expected frequency for color = 15.00000[0m
[0m[ INFO] [1556788079.379215934]: Start publisher IMU[0m
[0m[ INFO] [1556788079.381900206]: setupStreams...[0m
 02/05 11:07:59,383 WARNING [140523137537792] (sensor.cpp:366) Unregistered Media formats : [ UYVY ]; Supported: [ ]
[33m[ WARN] [1556787999.301279405]: If not further specified the default values for the dynamic reconfigurable parameters will be loaded.[0m
rocess[camera_side_left/realsense2_camera_manager-8]: started with pid [3917][0m
[1mprocess[camera_side_left/realsense2_camera-9]: started with pid [3919][0m
[1mprocess[camera_side_right/realsense2_camera_manager-10]: started with pid [3921][0m
[1mprocess[camera_side_right/realsense2_camera-11]: started with pid [3925][0m
[1mprocess[rviz-22]: started with pid [4066][0m

**Comment by schmidtp1** [comment]
Hi @Hunk86,

Did you try this with the latest development? (https://github.com/IntelRealSense/realsense-ros/commit/b4b863d19b0a5c968fd882c81f03535259a7d5f2)

**Comment by doronhi** [comment]
Is the problem solved by 

> Hi @Hunk86,
> 
> Did you try this with the latest development? ([b4b863d](https://github.com/IntelRealSense/realsense-ros/commit/b4b863d19b0a5c968fd882c81f03535259a7d5f2))

Is the problem solved?
If not, I added [PR 775](https://github.com/IntelRealSense/realsense-ros/pull/775) that is more resilient to conflicting devices. I tried it with 3 cameras and it worked for me.

**Comment by Hunk86** [comment]
No the problem isn't solved. I've updated to :+1: 
 [ INFO] [1558624198.529168823]: Running with LibRealSense v2.22.0
[ INFO] [1558624198.540920248]: RealSense ROS v2.2.4

and get more errors:

` 23/05 17:10:12,529 ERROR [140455280654080] (types.h:243) xioctl(VIDIOC_S_FMT) failed Last Error: Input/output error
[ERROR] [1558624212.529618403]: An exception has been thrown: xioctl(VIDIOC_S_FMT) failed Last Error: Input/output error
 23/05 17:10:12,529 ERROR [140455280654080] (context.cpp:433) Exception thrown from user callback handler
[ WARN] [1558624213.296061464]: Hardware Notification:Motion Module force pause,1.55862e+12,Error,Hardware Error
[ERROR] [1558624213.296204599]: Hardware Reset is needed. use option: initial_reset:=true
 23/05 17:10:14,380 ERROR [140454280554240] (types.h:243) xioctl(VIDIOC_DQBUF) failed for fd: 33 Last Error: No such device
 23/05 17:10:14,380 ERROR [140454280554240] (backend-v4l2.cpp:1230) xioctl(VIDIOC_DQBUF) failed for fd: 33 Last Error: No such device
[ WARN] [1558624214.380548636]: Hardware Notification:xioctl(VIDIOC_DQBUF) failed for fd: 33 Last Error: No such device,1.55862e+12,Error,Unknown Error
 23/05 17:10:14,401 ERROR [140455244650240] (types.h:243) Cannot open '/dev/video12 Last Error: No such file or directory
 23/05 17:10:14,401 ERROR [140455244650240] (global_timestamp_reader.cpp:152) Error during time_diff_keeper polling: Cannot open '/dev/video12 Last Error: No such file or directory
 23/05 17:10:14,410 ERROR [140454741923584] (types.h:243) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 23/05 17:10:14,410 ERROR [140454741923584] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 23/05 17:10:17,514 WARNING [140454704514816] (backend-hid.cpp:572) iio_hid_sensor: Frames didn't arrived within 5 seconds
 23/05 17:10:17,515 WARNING [140454712907520] (backend-hid.cpp:572) iio_hid_sensor: Frames didn't arrived within 5 seconds
[ERROR] [1558624217.539764693]: The device has been disconnected!
 23/05 17:10:17,574 ERROR [140455280654080] (types.h:243) xioctl(VIDIOC_STREAMOFF) failed for buf_type=1 Last Error: No such device
 23/05 17:10:17,574 ERROR [140455280654080] (sensor.cpp:260) An error has occurred while stop_streaming()!
 23/05 17:10:17,575 WARNING [140454976788224] (backend-hid.h:48) write_fs_attribute with 0 failed. The specified path /sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.5/0003:8086:0B3A.0013/HID-SENSOR-200076.6.auto/iio:device5/buffer/enable is not valid
 23/05 17:10:17,575 WARNING [140454976788224] (backend-hid.cpp:666) HID set_power 0 failed for /sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.5/0003:8086:0B3A.0013/HID-SENSOR-200076.6.auto/iio:device5/buffer/enable
 23/05 17:10:17,576 WARNING [140454985180928] (backend-hid.h:48) write_fs_attribute with 0 failed. The specified path /sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.5/0003:8086:0B3A.0013/HID-SENSOR-200073.5.auto/iio:device1/buffer/enable is not valid
 23/05 17:10:17,576 ERROR [140455280654080] (types.h:243) Failed to enable_sensor /sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.5/0003:8086:0B3A.0013/HID-SENSOR-2000e1.7.auto/enable_sensor Last Error: No such file or directory
 23/05 17:10:17,576 ERROR [140455280654080] (sensor.cpp:805) An error has occurred while stop_streaming()!
 23/05 17:10:17,576 WARNING [140454985180928] (backend-hid.cpp:666) HID set_power 0 failed for /sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.5/0003:8086:0B3A.0013/HID-SENSOR-200073.5.auto/iio:device1/buffer/enable
 23/05 17:10:17,576 WARNING [140455280654080] (backend-hid.cpp:614) open() failed!
 23/05 17:10:17,581 WARNING [140455280654080] (backend-hid.cpp:614) open() failed!
 23/05 17:10:17,586 WARNING [140455280654080] (backend-hid.cpp:614) open() failed!
 23/05 17:10:17,591 WARNING [140455280654080] (backend-hid.cpp:614) open() failed!
 23/05 17:10:17,596 WARNING [140455280654080] (backend-hid.cpp:614) open() failed!
 23/05 17:10:17,601 WARNING [140455280654080] (backend-hid.cpp:614) open() failed!
 23/05 17:10:17,607 WARNING [140455280654080] (backend-hid.cpp:614) open() failed!
 23/05 17:10:17,612 WARNING [140455280654080] (backend-hid.cpp:614) open() failed!
 23/05 17:10:17,617 WARNING [140455280654080] (backend-hid.cpp:614) open() failed!
 23/05 17:10:17,622 ERROR [140455280654080] (types.h:243) open() failed with all retries! Last Error: No such file or directory
`

This commit is a part of release 2.2.4 ... so this hasn't any effect

Which kernel are you using ?

**Comment by Hunk86** [comment]
And which Backend are you using ?

I found some hacks here :
https://github.com/IntelRealSense/librealsense/issues/2850#issuecomment-445460696

**Comment by doronhi** [comment]
My kernel version is:
`
4.15.0-47-generic
`
I don't understand the question about the backends. Could you clarify?
Rereading your original post I see now that I didn't check it with Ubuntu18.04 and also, not with 3 D435i but with 2 and a T265. Maybe that's a significant difference.
I'll let you know when I found something useful.

**Comment by Hunk86** [comment]
If you are using the flag -DFORCE_LIBUVC=true ?

I've updated the system to 
ros-realsense: 2.2.6
librealsense: v2.23.0

I've tested the setup now with different number of cameras. With 2 it is working, but I receive the limit on 4 cameras.

At the moment I get an exception rs2::invalid_value_error

![crash](https://user-images.githubusercontent.com/5208198/59340202-cc182c80-8d05-11e9-9a59-75e46392160c.png)

When we start the 4 cameras with sleep between the launch file it is working

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @Hunk86,

Please provide us with the following details about your system configuration :
FW version on each camera
ROS distribution version
HW configuration details (platforms names, how the camera(s) is/are connected, etc)

Thank you!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@Hunk86,

Do you still need help with this question?

**Comment by Vivoslespagnos** [comment]
Hi, I'm on Ubuntu 18.04(LTS), Kernel 5.0.0-36-generic x86_64, ROS Melodic and i have the same error message about UVC data from "ds5-timestamps.cpp:64". 
I dowloaded Realsense2.0 SDK last upgrade : https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md &&  https://github.com/intel-ros/realsense#step-3-install-intel-realsense-ros-from-sources 

But it's doesn't work ! I don't know why ! 

thx u
